# Generated by Django 4.0.1 on 2023-05-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='athor',
            new_name='author',
        ),
    ]
